development:
  adapter: postgresql
  encoding: unicode
  database: test_app_dev
  pool: 5
  host: localhost
  port: 5432
  username: postgres
  password: password

production:
  adapter: postgresql
  encoding: unicode
  database: test_app_production
  pool: 5
  host: localhost
  port: 5432
  username: postgres
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: test_app_test
  pool: 5
  host: localhost
  port: 5432
  username: postgres
  password: password
